title: Bioinformatician Min
description: sharing my study, experience and code
theme: minima
author: Min


markdown: kramdown
kramdown:
  input: GFM          # 使用 GitHub 风格 Markdown
  toc_levels: 1..3    # TOC 包含的标题层级
  auto_ids: true      # 自动生成锚点
